[package]
name = "DiscordDubstepBot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
serenity = { version = "0.12.5", features = ["voice"] }
dotenv = "0.15"
vosk = "0.3.1"
cpal = "0.15"
dasp = "0.11"
hound = "3.5"
